status:
  state: online
spec:
  workflows:
  - path: src/schedule-workflow.py
    schedule: '*/10 * * * *'
    name: testing-schedule
  - path: src/schedule-workflow.py
    name: main
  desired_state: online
  source: git://github.com/xsqian/mlrun-github-example.git#main
  load_source_on_run: true
  origin_url: git://github.com/xsqian/mlrun-github-example.git#refs/heads/main
  owner: xingsheng
  functions:
  - url: src/func1.py
    name: function1
    kind: job
    image: mlrun/mlrun
    handler: handler
    with_repo: true
  - url: src/nucl.py
    name: nuc-a-workflow
    kind: nuclio
    image: mlrun/mlrun
  - url: src/nucl.py
    name: main
    kind: nuclio
    image: mlrun/mlrun
  conda: ''
metadata:
  created: '2024-10-08T16:36:59.446000'
  name: schedule-workflow
kind: project
