kind: project
metadata:
  name: nodegroup-test
  created: '2024-06-07T16:29:26.943000'
spec:
  functions:
  - url: my_job_code.py
    name: greetings
    kind: job
    image: mlrun/mlrun:1.4.1
    handler: handler
    with_repo: true
  - url: coffeerating-data-generator.py
    name: coffeerating-data-function
    kind: job
    image: mlrun/mlrun:1.6.1
    handler: coffeerating_data_generator
    with_repo: true
  - url: trainer.py
    name: coffeerating-trainer
    kind: job
    image: mlrun/mlrun:1.6.1
    handler: train
    with_repo: true
  - url: src/func1.py
    name: function1
    kind: job
    image: mlrun/mlrun:1.4.1
    handler: handler
    with_repo: true
  - url: functions/nodegroup_test.py
    name: nodegroup-test
    kind: job
    image: mlrun/mlrun:1.6.1
    handler: nodegroup_test
    with_repo: true
  workflows:
  - path: workflow.py
    name: main
  - path: ./schedule-workflow.py
    name: testing
    schedule: '*/10 * * * *'
  - path: ./schedule-workflow.py
    name: testing-scheduled-workflow
    schedule: '*/10 * * * *'
  - path: src/schedule-workflow.py
    name: testing-schedule
    schedule: '*/10 * * * *'
  - path: workflow/workflow.py
    name: workflow
    handler: test
  artifacts: []
  conda: ''
  source: git://github.com/xsqian/mlrun-github-example.git#main
  origin_url: git://github.com/xsqian/mlrun-github-example.git#refs/heads/main
  load_source_on_run: true
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
